
-- Drop table

-- DROP TABLE example.student;

CREATE TABLE example.student (
	student_id uuid NOT NULL,
	student_name varchar(50) NOT NULL,
	class_room varchar(30) NOT NULL,
	CONSTRAINT student_pk PRIMARY KEY (student_id)
);



DROP TYPE IF EXISTS STUDENT_MAP CASCADE;
CREATE TYPE STUDENT_MAP AS (CLASS_NAME TEXT, STUDENT_NUMBER INTEGER);

CREATE OR REPLACE FUNCTION EXAMPLE.LIST_STUDENTS_EACH_CLASS()
	RETURNS SETOF STUDENT_MAP
	LANGUAGE PLPGSQL
AS $$
	BEGIN
		RETURN QUERY SELECT ES.CLASS_ROOM:: TEXT AS CLASS_NAME, COUNT(ES.STUDENT_ID)::INTEGER AS STUDENT_NUMBER  FROM EXAMPLE.STUDENT AS ES GROUP BY ES.CLASS_ROOM;
	END;
$$
;
