
-- Drop table

DROP TABLE IF EXISTS example.student;

CREATE TABLE EXAMPLE.STUDENT (
	STUDENT_ID UUID NOT NULL,
	STUDENT_NAME VARCHAR(50) NOT NULL,
	CLASS_ROOM VARCHAR(30) NOT NULL,
	CONSTRAINT STUDENT_PK PRIMARY KEY (STUDENT_ID)
);



DROP TYPE IF EXISTS STUDENT_MAP CASCADE;

CREATE TYPE STUDENT_MAP AS (CLASS_NAME TEXT, STUDENT_NUMBER INTEGER);

CREATE OR REPLACE FUNCTION EXAMPLE.LIST_STUDENTS_EACH_CLASS()
	RETURNS SETOF STUDENT_MAP
AS 
'
	BEGIN
		RETURN QUERY SELECT ES.CLASS_ROOM:: TEXT AS CLASS_NAME, COUNT(ES.STUDENT_ID)::INTEGER AS STUDENT_NUMBER  
		FROM EXAMPLE.STUDENT AS ES 
		GROUP BY ES.CLASS_ROOM;
	END;
'
LANGUAGE PLPGSQL;